# Generated by Django 5.1.5 on 2025-01-31 20:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faqs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer_bn",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_bn",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_hi",
            field=models.TextField(blank=True),
        ),
    ]
