# Generated by Django 5.1.5 on 2025-01-31 20:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faqs", "0003_remove_faq_answer_bn_remove_faq_answer_hi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(
                help_text="Answer in default language (English)"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(
                help_text="Question in default language (English)"
            ),
        ),
        migrations.CreateModel(
            name="FAQTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("bn", "Bengali"),
                        ],
                        max_length=10,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", ckeditor.fields.RichTextField()),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="faqs.faq",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Translation",
                "verbose_name_plural": "FAQ Translations",
                "unique_together": {("faq", "language")},
            },
        ),
    ]
