# Generated by Django 5.1.5 on 2025-01-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faqs", "0004_alter_faq_answer_alter_faq_question_faqtranslation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={},
        ),
        migrations.AlterModelOptions(
            name="faqtranslation",
            options={},
        ),
        migrations.AlterField(
            model_name="faqtranslation",
            name="language",
            field=models.CharField(max_length=2),
        ),
    ]
