# Generated by Django 5.1.5 on 2025-02-01 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "faqs",
            "0005_alter_faq_options_alter_faqtranslation_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AlterModelOptions(
            name="faqtranslation",
            options={
                "verbose_name": "FAQ Translation",
                "verbose_name_plural": "FAQ Translations",
            },
        ),
    ]
