# Generated by Django 5.1.5 on 2025-02-01 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faqs", "0006_alter_faq_options_alter_faqtranslation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqtranslation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="faqtranslation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
